name: smbioslib_ci

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: OS Version
      run: uname -a
    - name: Run tests
      run: cargo test --verbose