name: smbioslib_ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: ${{ github.event.label.name == 'Ready for Review' }} || github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install nightly (Linux)
      run: rustup toolchain install nightly
      if:  matrix.os == 'ubuntu-latest'
    - name: Build no_std with nightly
      run: cargo +nightly build --features no_std,x86_64 --lib
      if:  matrix.os == 'ubuntu-latest'